### ISSUE TITLE
Bug? Sign column seems off

### ISSUE THREAD

**Issue by nat-418** [atelierbram/Base2Tone-nvim#2]
This doesn't look quite right, almost like the sign column is inverted? Using the git signs plugin here, same happens with marks in the sign column.

Desert Dark:
![image](https://user-images.githubusercontent.com/93013864/198693130-dc70fe68-7ec5-4123-b1cd-4ed3a5badef6.png)

Garden Dark:

![image](https://user-images.githubusercontent.com/93013864/198693359-06b6baf7-d46a-4e5a-9482-e7870a2f6cb9.png)

**Comment by atelierbram** [comment]
@nat-418 thanks for the feedback. Indeed this was an oversight, should be fixed now. I also changed the line-number background-color - to be the same as the "normal" background - in order to have a bit more breathing room (like left aligned code not so awkwardly edging the left margin). But please let me know if this works for you after updating.

**Comment by nat-418** [comment]
looks better for the git signs.  there's still an issue with marks signs and some other sign column stuff

![image](https://user-images.githubusercontent.com/93013864/198740131-6c4ee965-b3e0-479d-bbe6-45554d9c4f06.png)

![image](https://user-images.githubusercontent.com/93013864/198740191-e2e971a4-5770-43d0-8679-1b706ba2366d.png)

**Comment by atelierbram** [comment]
@nat-418 thanks for the quick reaction. The latest commit makes the text appear in better contrast (without those boxy background colors) IMO, but let me know what you think.

**Comment by nat-418** [comment]
Still not working for the marks column    https://github.com/chentoast/marks.nvim

**Comment by atelierbram** [comment]
@nat-418 That's hilarious 😃  never heard of this plugin before but I like it &hellip; a lot! So there you go: support for marks plugin with the latest commit.

**Comment by nat-418** [comment]
Yeah it's nice to be able to see the marks. Great work on the colorschemes. I personally prefer more low-contrast ones, but these look good.
